### ISSUE TITLE
Phptinker

### ISSUE THREAD

**Issue by swapnilsarwe** [swapnilsarwe/whatsapp-conversation-parser#1]
@phptinker

```php
echo "Hello World";
```

**Comment by phptinker** [comment]
@swapnilsarwe, here's the evaluated code:

```
Hello World
```

<details>
<summary>We evaluated this code</summary>

```php
echo "Hello World";
```
</details>

Check out [Tinkerwell](https://tinkerwell.app) for even easier code evaluation.
